version: "3"

services:
  rmbg:
    container_name: rmbg
    build:
      context: .
      dockerfile: ./apps/rmbg/Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
